### ISSUE TITLE
execute dataBaseSchema error

### ISSUE THREAD

**Issue by phuocle** [DigitalFlow/Open-Certification-Trainer#4]
+ I install PostgreSQL successed. v.10
+ Open pgAdmin 4
+ Create new DB: certification success.
+ Open query tool after created db. Then open file: dataBaseSchema.
+ Press F5 to execute script and I get the error below

```
ERROR:  syntax error at or near "f39f13b4"
LINE 140: f39f13b4-b8c6-4013-ace6-087a45dbd23d root root@local.domain ...
          ^
SQL state: 42601
Character: 3370
```

Please help me how I can fix it.

Thanks.

**Comment by DigitalFlow** [comment]
Hey @phuocle,

Thanks for giving it a try.
I'll have to improve on the install guide, sorry for that.

For importing the backup, you should use psql, which is bundled with PostgreSql server.
For me it was installed at `C:\Program Files\PostgreSQL\10\bin`. I added it to my windows path, so that it can be used without having to specify the full folder every time.

For importing the database schema:
`psql -U postgres -h localhost -d postgres -f "C:\Open-Certification-Trainer\dataBaseSchema.sql"`

Where -U is the user name of your root user (usually postgres), -h is the server (can be ommitted if localhost), -d is the database (postgres is the default database) and -f is the file location of your database schema.
Please give me a quick note, whether the import succeeded like this.

Kind Regards,
Florian

**Comment by phuocle** [comment]
Thanks @DigitalFlow, it worked now.

One more question, when I run website, I sign up success, and then login. But I login with end user.

How I can login with admin user.

Thanks,
Phuoc

**Comment by DigitalFlow** [comment]
Hi @phuocle,

awesome that it is working for you!

There is a default root user with user name root and password root.
You can login with it, then it would probably be a good idea to change his password.

Just give me a quick note, once you were able to login.

Kind Regards,
Florian

**Comment by phuocle** [comment]
Hi @DigitalFlow 

Everything ok now.

Now i try learn howto publish  to my sub-domain site. E.g: http://certification.mydomain.com

Question: Can I host it on IIS. I have a Win2012Server

**Comment by DigitalFlow** [comment]
Hi @phuocle,

It should work using [iisnode](https://tomasz.janczuk.org/2011/08/hosting-express-nodejs-applications-in.html).
I didn't try it yet, so if you do please give me some feedback, if you got it working like that.
I'm using [forever](https://github.com/foreverjs/forever) for publishing it constantly right now.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @phuocle,

Did you  get it to work on IIS?
I'll close this task for now, please reopen or create another one if you need more information.

Kind Regards,
Florian
